default_language_version:
    python: python3.7

default_stages: [commit, push]
fail_fast: true

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    # ensures files are either empty or end with a blank line
    -   id: end-of-file-fixer
    # valid python file
    -   id: check-ast
    # validates style
    -   id: flake8

-   repo: local
    hooks:
      - id: mypy
        name: Check mypy static types match
        entry: poetry run mypy .
        types: [python]
        language: python
