version: "3.6"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    env_file:
      - .env
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_MIGRATIONS_DIR: "./hasura/migrations"
  bot:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - auxil:/data
volumes:
  db_data:
  auxil:
